const List<String> stations = [
  "Manjeri",
  "Alappuzha",
  "Thrissur",
  "Wandoor",
  "Malappuram",
  "Kondotty",
  "Kozhikode",
  "Kannur",
  "Kasaragod",
  "Kollam",
  "Kottayam",
  "Kochi",
  "Thiruvananthapuram",
  "Palakkad",
  "Kodungallur",
  "Kottakkal",
  "Ernakulam South",
  "Thalassery",
  "Valanchery",
  "Koyilandy",
  "Vadakara",
  "Wayanad",
];
